# Generated by Django 3.0.5 on 2020-04-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='number',
            field=models.IntegerField(blank=True, choices=[('', 'No Rank')], null=True),
        ),
    ]
