# Generated by Django 3.0.5 on 2020-04-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20200405_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='number',
            field=models.IntegerField(blank=True, choices=[('', 'No Rank'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True),
        ),
    ]
