# Generated by Django 3.0.3 on 2020-03-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20200323_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='review',
            field=models.TextField(),
        ),
    ]
