# Generated by Django 3.0.3 on 2020-03-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_auto_20200323_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='review',
        ),
    ]
