# Generated by Django 3.0.5 on 2020-04-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_rank_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
