# Generated by Django 3.0.3 on 2020-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-movie.png', upload_to='movie_posters')),
                ('title', models.CharField(max_length=60)),
                ('overview', models.TextField()),
                ('phase', models.IntegerField()),
                ('release_date', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
