# Generated by Django 3.0.4 on 2020-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
