# Generated by Django 3.1.1 on 2020-10-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20200924_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='teaser',
            field=models.ImageField(default='default-movie.png', upload_to='movie_teasers'),
        ),
    ]
