# Generated by Django 3.1.1 on 2020-10-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20201026_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='teaser',
            field=models.ImageField(default='teaser-default.gif', upload_to='movie_teasers'),
        ),
    ]
